### ISSUE TITLE
[Issue]: Failing Unit Tests

### ISSUE THREAD

**Issue by pvelesko** [ROCm-Developer-Tools/hip-tests#462] opened 2024-05-13 10:03 UTC
### Problem Description

```
The following tests FAILED:
          6 - Unit_hiprtc_devicemalloc (Failed)
         29 - Unit_deviceAllocation_Malloc_PerThread_PrimitiveDataType (Failed)
         30 - Unit_deviceAllocation_New_PerThread_PrimitiveDataType (Failed)
         31 - Unit_deviceAllocation_Malloc_PerThread_StructDataType (Failed)
         32 - Unit_deviceAllocation_New_PerThread_StructDataType (Failed)
         34 - Unit_deviceAllocation_Malloc_AcrossKernels (Failed)
         35 - Unit_deviceAllocation_New_AcrossKernels (Failed)
         37 - Unit_deviceAllocation_New_ComplexDataType (Failed)
         38 - Unit_deviceAllocation_Malloc_UnionType (Failed)
         39 - Unit_deviceAllocation_New_UnionType (Failed)
         40 - Unit_deviceAllocation_Malloc_SingleCodeObj (Failed)
         41 - Unit_deviceAllocation_New_SingleCodeObj (Failed)
         42 - Unit_deviceAllocation_Malloc_PerThread_Graph (Failed)
         43 - Unit_deviceAllocation_New_PerThread_Graph (Failed)
         44 - Unit_deviceAllocation_Malloc_DeviceFunc (Failed)
         45 - Unit_deviceAllocation_New_DeviceFunc (Failed)
         46 - Unit_deviceAllocation_VirtualFunction (Failed)
         47 - Unit_deviceAllocation_Malloc_MulKernels_MulThreads (Failed)
         48 - Unit_deviceAllocation_New_MulKernels_MulThreads (Failed)
         49 - Unit_deviceAllocation_Malloc_SingKernels_MulThreads (Failed)
         50 - Unit_deviceAllocation_New_SingKernels_MulThreads (Failed)
         51 - Unit_deviceAllocation_Malloc_MulCodeObj (Failed)
         52 - Unit_deviceAllocation_New_MulCodeObj (Failed)
        746 - Unit_hipMemPrefetchAsync_NonPageSz (Failed)
        777 - Unit_hipHostMalloc_CoherentTst (Bus error)
        778 - Unit_hipMallocManaged_CoherentTst (Bus error)
        1094 - Unit_hipMemPrefetchAsync_Basic (Failed)
        1243 - test_svm_fine_grain_memory_consistency (Bus error)
        1244 - test_svm_fine_grain_sync_buffers (Bus error)
        1518 - Unit_printf_flags (Failed)
        1519 - Unit_printf_specifier (Failed)
        1520 - Unit_Buffered_Printf_Flags (Failed)
        1521 - Unit_Buffered_Printf_Specifier (Failed)
        1522 - Unit_Host_Printf (Failed)
        1944 - Unit_hipStreamPerThread_MangdMem (Failed)
        1965 - Unit_kernel_ChkPrintf (Failed)
        2018 - Unit_hipCGMultiGridGroupType_Basic (Bus error)
        2019 - Unit_hipCGMultiGridGroupType_Barrier (Timeout)
        2020 - Unit_hipCGGridGroupType_Basic (Failed)
        2021 - Unit_hipCGGridGroupType_DataSharing (SEGFAULT)
        2022 - Unit_hipCGGridGroupType_Barrier (SEGFAULT)
        2023 - Unit_hipCGThreadBlockTileType (Failed)
        2024 - Unit_hipCGThreadBlockTileType_Shfl (Failed)
        2025 - Unit_coalesced_groups (Failed)
        2026 - Unit_hipLaunchCooperativeKernel_Basic (Failed)
        2028 - Unit_hipLaunchCooperativeKernelMultiDevice_Basic (Failed)
        2029 - Unit_hipLaunchCooperativeKernelMultiDevice_Streams (Failed)
        2030 - Unit_Grid_Group_Getters_Positive_Basic (Failed)
        2031 - Unit_Grid_Group_Getters_Via_Non_Member_Functions_Positive_Basic (Failed)
        2032 - Unit_Grid_Group_Sync_Positive_Basic (Failed)
        2033 - Unit_coalesced_groups_shfl_down (Subprocess aborted)
        2034 - Unit_coalesced_groups_shfl_up (Subprocess aborted)
        2035 - Unit_tiled_groups_metagrp_basic (Failed)
        2036 - Unit_coalesced_groups_metagrp_basic (Failed)
        2037 - Unit_hipDeviceGetPCIBusId_Functional (Failed)
        2038 - Unit_hipDrvMemcpy_Functional (Failed)
        2039 - Unit_hipMemsetD8_Functional (Failed)
        2056 - Unit_dynamic_loading_device_kernels_from_library (Subprocess aborted)
        2057 - Unit_hipApiDynamicLoad (Subprocess aborted)
        2058 - Unit_dynamic_loading_device_kernels_from_library (Subprocess aborted)
        2059 - Unit_hipApiDynamicLoad (Subprocess aborted)
        2060 - Unit_hipMalloc_gpptest (Failed)
        2063 - Unit_hipExtModuleLaunchKernel_UniformWorkGroup (Failed)
        2064 - Unit_KerArgOptimization_Saxpy (Failed)
        2133 - Unit_dim3_Empty_Positive_Device (Failed)
        2134 - Unit_dim3_X_Positive_Device (Failed)
        2135 - Unit_dim3_XY_Positive_Device (Failed)
        2136 - Unit_dim3_XYZ_Positive_Device (Failed)
        2147 - Unit_atomicExch_Positive - int (Failed)
        2148 - Unit_atomicExch_Positive - unsigned int (Failed)
        2149 - Unit_atomicExch_Positive - unsigned long (Failed)
        2150 - Unit_atomicExch_Positive - unsigned long long (Failed)
        2151 - Unit_atomicExch_Positive - float (Failed)
        2152 - Unit_atomicExch_Positive - double (Failed)
        2159 - Unit_atomicExch_Negative_Parameters_RTC (Failed)
        2178 - Unit_atomicExch_system_Negative_Parameters_RTC (Failed)
        2181 - Unit_hipP2pLinkTypeAndHopFunc (Failed)
        2182 - Unit_LaunchKernelgccTests (Failed)
        2186 - Unit_hipGetStreamDeviceId_Positive_Threaded_Basic (SEGFAULT)
        2187 - Unit_hipGetStreamDeviceId_Positive_Multithreaded_Basic (Failed)
        2188 - Unit_hipGetStreamDeviceId_Negative_Parameters (SEGFAULT)
        2189 - Unit_hipKernelNameRef_Positive_Basic (Failed)
        2191 - Unit_hipKernelNameRefByPtr_Positive_Basic (Failed)
        2193 - Unit_hipKernelNameRefByPtr_Negative_KernelNullptr (Failed)
        2194 - Unit_hipClock64_Positive_Basic (Failed)
        2195 - Unit_hipClock_Positive_Basic (Failed)
        2196 - Unit_hipWallClock64_Positive_Basic (Failed)
        2197 - ABM_AddKernel_MultiTypeMultiSize - int (Failed)
        2198 - ABM_AddKernel_MultiTypeMultiSize - long (Failed)
        2199 - ABM_AddKernel_MultiTypeMultiSize - float (Failed)
        2200 - ABM_AddKernel_MultiTypeMultiSize - long long (Failed)
        2201 - ABM_AddKernel_MultiTypeMultiSize - double (Failed)
        2202 - Unit_hipManagedKeyword_SingleGpu (SEGFAULT)
        2203 - Unit_hipManagedKeyword_MultiGpu (SEGFAULT)
        2204 - ChildMalloc (Failed)
        2207 - Unit_hipDeviceGetPCIBusId_CheckPciBusIDWithLspci (Failed)
        2210 - Unit_hipGetDeviceCount_MaskedDevices (Failed)
        2212 - Unit_hipSetDevice_InvalidVisibleDeviceList (Failed)
        2213 - Unit_hipSetDevice_ValidVisibleDeviceList (Failed)
        2214 - Unit_hipSetDevice_SubsetOfAvailableDevices (Failed)
        2215 - Unit_hipSetDevice_MinRvdMaxHvdDevicesList (Failed)
        2216 - Unit_hipSetDevice_MaxRvdMinHvdDevicesList (Failed)
        2217 - Unit_hipSetDevice_RvdCvdDevicesList (Failed)
        2218 - Unit_hipIpcMemAccess_Semaphores (Failed)
        2220 - Unit_hipMalloc_ChildConcurrencyDefaultGpu (Failed)
        2221 - Unit_hipMalloc_ChildConcurrencyMultiGpu (Failed)
        2222 - Unit_malloc_CoherentTst (Subprocess aborted)
        2223 - Unit_malloc_CoherentTstWthAdvise (Subprocess aborted)
        2224 - Unit_mmap_CoherentTst (Subprocess aborted)
        2225 - Unit_mmap_CoherentTstWthAdvise (Subprocess aborted)
        2226 - Unit_hipHostMalloc_WthEnv0Flg1 (Failed)
        2227 - Unit_hipHostMalloc_WthEnv0Flg2 (Failed)
        2228 - Unit_hipHostMalloc_WthEnv0Flg3 (Failed)
        2229 - Unit_hipHostMalloc_WthEnv0Flg4 (Failed)
        2230 - Unit_hipHostMalloc_WthEnv1 (Failed)
        2231 - Unit_hipHostMalloc_WthEnv1Flg1 (Failed)
        2232 - Unit_hipHostMalloc_WthEnv1Flg2 (Failed)
        2233 - Unit_hipHostMalloc_WthEnv1Flg3 (Failed)
        2234 - Unit_hipIpcEventHandle_Functional (Failed)
        2235 - Unit_hipIpcEventHandle_ParameterValidation (Failed)
        2236 - Unit_deviceAllocation_Malloc_MultProcess (Failed)
        2237 - Unit_deviceAllocation_New_MultProcess (Failed)
        2238 - Unit_deviceAllocation_MallocFree_MultProcess (Failed)
        2239 - Unit_deviceAllocation_NewDelete_MultProcess (Failed)
        2242 - Unit_NoGpuTst_hipDeviceGetAttribute (Failed)
        2243 - Unit_NoGpuTst_hipDeviceGetP2PAttribute (Failed)
        2244 - Unit_NoGpuTst_hipDeviceGetPCIBusId (Failed)
        2245 - Unit_NoGpuTst_hipDeviceGetByPCIBusId (Failed)
        2246 - Unit_NoGpuTst_hipDeviceTotalMem (Failed)
        2247 - Unit_NoGpuTst_hipFuncSetSharedMemConfig (Failed)
        2248 - Unit_NoGpuTst_hipStreamCreate (Failed)
        2249 - Unit_NoGpuTst_hipStreamCreateWithPriority (Failed)
        2250 - Unit_NoGpuTst_hipStreamSynchronize (Failed)
        2251 - Unit_NoGpuTst_hipStreamGetFlags (Failed)
        2252 - Unit_NoGpuTst_hipExtStreamCreateWithCUMask (Failed)
        2253 - Unit_NoGpuTst_hipStreamAddCallback (Failed)
        2254 - Unit_NoGpuTst_hipEventCreateWithFlags (Failed)
        2255 - Unit_NoGpuTst_hipDeviceSynchronize (Failed)
        2256 - Unit_NoGpuTst_hipGetDevice (Failed)
        2257 - Unit_NoGpuTst_hipDeviceGetCacheConfig (Failed)
        2258 - Unit_NoGpuTst_hipDeviceGetSharedMemConfig (Failed)
        2259 - Unit_NoGpuTst_hipDeviceSetSharedMemConfig (Failed)
        2260 - Unit_NoGpuTst_hipPointerGetAttributes (Failed)
        2261 - Unit_NoGpuTst_hipExtMallocWithFlags (Failed)
        2262 - Unit_NoGpuTst_hipMallocManaged (Failed)
        2263 - Unit_NoGpuTst_hipHostFree (Failed)
        2264 - Unit_NoGpuTst_hipMemcpyWithStream (Failed)
        2265 - Unit_NoGpuTst_hipMallocArray (Failed)
        2266 - Unit_NoGpuTst_hipMallocMipmappedArray (Failed)
        2267 - Unit_NoGpuTst_hipDeviceEnablePeerAccess (Failed)
        2268 - Unit_NoGpuTst_hipHostMalloc (Failed)
        2269 - Unit_NoGpuTst_hipMalloc (Failed)
        2270 - Unit_NoGpuTst_hipHostRegister (Failed)
        2271 - Unit_NoGpuTst_hipMemcpy (Failed)
        2272 - Unit_NoGpuTst_hipMemAllocPitch (Failed)
        2273 - Unit_NoGpuTst_hipMemGetInfo (Failed)
        2274 - Unit_NoGpuTst_hipMalloc3DArray (Failed)
        2275 - Unit_NoGpuTst_hipDeviceCanAccessPeer (Failed)
        2276 - Unit_NoGpuTst_hipDeviceDisablePeerAccess (Failed)
        2277 - Unit_NoGpuTst_hipDeviceGet (Failed)
        2278 - Unit_NoGpuTst_hipDeviceComputeCapability (Failed)
        2279 - Unit_NoGpuTst_hipDeviceGetName (Failed)
        2280 - Unit_NoGpuTst_hipGetDeviceProperties (Failed)
        2281 - Unit_NoGpuTst_hipChooseDevice (Failed)
        2282 - Unit_NoGpuTst_hipExtGetLinkTypeAndHopCount (Failed)
        2283 - Unit_NoGpuTst_hipExtStreamGetCUMask (Failed)
        2284 - Unit_NoGpuTst_hipFuncSetAttribute (Failed)
        2285 - Unit_NoGpuTst_hipFuncSetCacheConfig (Failed)
        2286 - Unit_NoGpuTst_hipStreamCreateWithFlags (Failed)
        2287 - Unit_NoGpuTst_hipDeviceGetStreamPriorityRange (Failed)
        2288 - Unit_NoGpuTst_hipEventCreate (Failed)
        2289 - Unit_NoGpuTst_hipStreamGetPriority (Failed)
        2290 - Unit_NoGpuTst_hipDeviceReset (Failed)
        2291 - Unit_NoGpuTst_hipDeviceSetCacheConfig (Failed)
        2292 - Unit_NoGpuTst_hipDeviceGetLimit (Failed)
        2293 - Unit_NoGpuTst_hipGetDeviceFlags (Failed)
        2294 - Unit_NoGpuTst_hipSetDeviceFlags (Failed)
        2295 - Unit_NoGpuTst_hipModuleLoad (Failed)
        2296 - Unit_NoGpuTst_hipFuncGetAttributes (Failed)
        2297 - Unit_NoGpuTst_hipModuleLoadData (Failed)
        2299 - Unit_NoGpuTst_hipLaunchCooperativeKernel (Failed)
        2300 - Unit_NoGpuTst_hipLaunchCooperativeKernelMultiDevice (Failed)
        2301 - Unit_NoGpuTst_hipExtLaunchMultiKernelMultiDevice (Failed)
        2302 - Unit_NoGpuTst_hipOccupancyMaxActiveBlocksPerMultiprocessor (Failed)
        2303 - Unit_NoGpuTst_hipOccupancyMaxActiveBlocksPerMultiprocessorFlags (Failed)
        2304 - Unit_NoGpuTst_hipOccupancyMaxPotentialBlockSize (Failed)
        2308 - Unit_NoGpuTst_hipMallocPitch (Failed)
        2309 - Unit_NoGpuTst_hipMipmappedArrayCreate (Failed)
        2310 - Unit_NoGpuTst_hipMalloc3D (Failed)
        2311 - Unit_NoGpuTst_hipGraphCreate (Failed)
        2314 - Unit_hipMemGetInfo_Functional_Scenario1 (Failed)
        2315 - Unit_hipMemGetInfo_Functional_Scenario2 (Failed)
        2316 - Unit_hipMemGetInfo_Functional_Scenario3 (Failed)
        2317 - Unit_hipMemGetInfo_Functional_scenario4 (Failed)
        2318 - Unit_hipMemGetInfo_Functional_MultiDevice_Scenario5 (Failed)
        2319 - Unit_hipMemGetInfo_SetHiddenFreeMemFromChild (Failed)
        2320 - Unit_hipMemGetInfo_VerifyHiddenFreeMemForAllGpu (Failed)
        2321 - Performance_hipStreamWaitEvent (Failed)
        2322 - Performance_hipStreamGetFlags (Failed)
        2323 - Performance_hipStreamGetPriority (Failed)
        2324 - Performance_hipExtStreamCreateWithCUMask (Failed)
        2325 - Performance_hipExtStreamGetCUMask (Failed)
        2326 - Performance_hipStreamAddCallback (Failed)
        2327 - Performance_hipStreamWaitValue32 (Failed)
        2328 - Performance_hipStreamWaitValue64 (Failed)
        2329 - Performance_hipStreamWriteValue32 (Failed)
        2330 - Performance_hipStreamWriteValue64 (Failed)
        2331 - Performance_hipMallocAsync (Failed)
        2332 - Performance_hipFreeAsync (Failed)
        2333 - Performance_hipMemPoolCreate (Failed)
        2334 - Performance_hipMemPoolDestroy (Failed)
        2335 - Performance_hipMemPoolTrimTo (Failed)
        2336 - Performance_hipMemPoolSetAttribute (Failed)
        2337 - Performance_hipMemPoolGetAttribute (Failed)
        2338 - Performance_hipMemPoolSetAccess (Failed)
        2339 - Performance_hipMallocFromPoolAsync (Failed)
        2340 - Performance_hipMemPoolExportToShareableHandle (Failed)
        2341 - Performance_hipMemPoolImportFromShareableHandle (Failed)
        2342 - Performance_hipMemPoolExportPointer (Failed)
        2343 - Performance_hipMemPoolImportPointer (Failed)
        2344 - Performance_hipStreamCreate (Failed)
        2345 - Performance_hipStreamCreateWithFlags (Failed)
        2346 - Performance_hipStreamCreateWithPriority (Failed)
        2347 - Performance_hipStreamDestroy (Failed)
        2348 - Performance_hipDeviceGetStreamPriorityRange (Failed)
        2349 - Performance_hipStreamQuery (Failed)
        2350 - Performance_hipStreamSynchronize (Failed)
        2351 - Performance_hipEventCreate (Failed)
        2352 - Performance_hipEventCreateWithFlags (Failed)
        2353 - Performance_hipEventRecord (Failed)
        2354 - Performance_hipEventDestroy (Failed)
        2355 - Performance_hipEventSynchronize (Failed)
        2356 - Performance_hipEventElapsedTime (Failed)
        2357 - Performance_hipEventQuery (Failed)
        2358 - Performance_Example (Failed)
```

### Operating System

Ubuntu 

### CPU

13th Gen Intel(R) Core(TM) i9-13900K

### GPU

AMD Radeon VII

### ROCm Version

ROCm 6.1.0

### ROCm Component

HIP

**Comment by pvelesko** [comment] 2024-05-13 10:48
Attached ctest log 
[Uploading failedHipTests.txt…]()

**Comment by schung-amd** [comment] 2024-09-13 17:55
Hi @pvelesko, are the tests still failing in ROCm 6.2? I'm seeing several failures on my end, but I think they are unrelated to the ones you are seeing here.

**Comment by schung-amd** [comment] 2024-09-24 15:23
Closing as I'm unable to reproduce these test failures on ROCm 6.1.0 with Ubuntu 22.04. Make sure you're pulling the correct branch of the `hip-tests` repo, as there is a branch appropriate for each version of ROCm; for example, on ROCm 6.1, `git clone -b rocm-6.1.x https://github.com/ROCm/hip-tests.git`. Feel free to reopen or submit a new issue if you are still experiencing this issue.

**Closed as not planned by schung-amd** 2024-09-24 15:23 UTC
Labels: Under Investigation
